# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 57005
description: ボイチェン ボイスチェンジャー まとめ
baseurl: "/voice_changer_docs" # the subpath of your site, e.g. /blog
url: "https://calls-tack.github.io" # the base hostname & protocol for your site, e.g. http://example.com
theme: just-the-docs
# remote_theme: just-the-docs/just-the-docs@v0.4.0.rc2
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE", "lib/", "bin/", "README.md", "Rakefile", "vendor"]

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/57005_86.png"







# External navigation links
nav_external_links:
  - title: ついったー
    url: https://twitter.com/tack_vr_app

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "ページの先頭へ"

footer_content: "Copyright &copy; 2022 calls-tack. Published under the <a href=\"https://github.com/calls-tack/voice_changer_docs/blob/main/LICENSE\" target=\"_blank\">MIT License</a>."








plugins:
  - jekyll-feed
